language: python

# to run travis'es containerized system, can't use sude
sudo: false
python:
  - "2.7"

# command to install dependencies
install: pip install requests pcapy dpkt netaddr

# command to run tests
# script: nosetests -v netscan/tests.py
script: True

# http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
# install dependencies before build using apt-get
addons:
  apt:
    packages:
    - libpcap-dev
